import React from 'react'

const Help = ({ toggleHelp }) => {
    return (
        <div
            className='help-container'
            onClick={(e) => {
                if (![...e.target.classList].includes('help'))
                    toggleHelp(false)
            }}
        >
            <div className="help">
                <h2>Welcome to my RNN text generation app</h2>
                <h3>What are RNNs?</h3>
                <p>RNNs (recurrent neural networks) are deep learning models that are used to predict sequential data, where
                    the prediction at one timestep is dependent on the previous values of the data.</p>

                <p>In this case, models were trained to predict sequences of characters. For example, if the model has
                    seen the sequence 'Appl', it may predict that the next character is
                    'e' for 'Apple', or it may predict 'i' for 'Application'.</p>

                <p>The models in this application have learned to make these predictions based off of their data sources, which are books.
                    Each model attempts to replicate the distribution of characters in its data source, so the Harry Potter
                    model may predict 'r' after seeing 'Har' while the Crime and Punishment model may predict 'd' after seeing the same characters.
                    Long sequences of text can be generated by having the model predict a character, then using that
                    character to predict the next character and so on.</p>

                <h3>Using this App</h3>
                <p>
                    This application is pretty simple. You can choose the model that will be generating
                    your text by clicking the choose model button. Once you have chosen a model,
                    you can input a sequence that the model will use to generate a longer chunk of
                    text from.
                </p>
                <p>
                    Optionally, you can tweak the unpredictability parameter. Higher values of unpredictability
                    wll lead to more unlikely characters being chosen.
                </p>
                <p>Once you have specified your parameters, click generate to get your sequence.
                    <strong>Please note
                        that the server may be asleep when you send your first request, so it may take
                        longer than usual. Subsequent requests should be rather fast.</strong>
                </p>
            </div>
        </div>
    )
}

export default Help